version: '3'
services:
  #PHP Service
  php:
    image: local/php:7.2
    restart: unless-stopped
    tty: true
    ports:
      - "8000:8000"
    volumes:
    - ./:/var/www
    - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    #- ~/.composer/auth.json:/root/.composer/auth.json

  #MySQL Service
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    tty: true
    ports:
      - "13306:3306"
    environment:
      MYSQL_DATABASE: mysql
      MYSQL_ROOT_PASSWORD: mysql
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql/data:/var/lib/mysql-files/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
